### ISSUE TITLE
Support for Laravel 9

### ISSUE THREAD

**Issue by jamiesykescreode** [pawelmysior/laravel-publishable#3]
Hi,

I'm interesting in this package to provide functionality for making some models publishable. Just wondering if there are any plans to add Laravel 9 support in a new version? Laravel 9 requires PHP > 8.0 so may hinder any backwards compatability.

Happy to submit a PR with dependency bumps to make this happen but I wanted to check the project scope before putting the work in.

Cheers!

**Comment by pawelmysior** [comment]
Hey, thanks for the message. Feel free to submit a PR to add support for Laravel 9, thanks!

**Comment by jamiesykescreode** [comment]
Do you have any preferences for how you would like the update to be carried out? My thoughts are that there should be a 2.0 version specifically mentioned to be compatible with Laravel 9? This incorporates higher version numbers of dependencies (based on Laravel 9.0 at release) and will likely break backwards compatibility anyway due to how newer versions of PHP are structured.

Obviously a change like this would be easier but means that the test suite for newer versions of PHP is broken due to some incompatibilities:
![CleanShot 2022-07-15 at 15 08 17](https://user-images.githubusercontent.com/22323384/179240216-6005a84a-51f2-4593-b42c-2795dca53278.png)

**Comment by jamiesykescreode** [comment]
#4

**Comment by jaymeh** [comment]
Commit has been merged now into a new 2.x branch @pawelmysior

Due to this I'm wanting to make 2.x the default branch and remove the master one. I also want to add protection to *.x branches going forwards. Just wondering if this is something you could help with/could grant me access to? 

Thanks
